### ISSUE TITLE
Maven BOMs are ignored

### ISSUE THREAD

**Issue by dasJ** [tadfisher/gradle2nix#15]
Maven supports [BOM dependencies](https://howtodoinjava.com/maven/maven-bom-bill-of-materials-dependency/).
These are specified as:
```xml
      <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-bom</artifactId>
        <version>${micrometer.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

```

For some reason, Gradle2nix doesn't seem to resolve them, resulting in a missing dependency on `nix-build`.

**Comment by dasJ** [comment]
PR adding BOM support to Gradle: https://github.com/gradle/gradle/pull/3383

**Comment by tadfisher** [comment]
Interesting, I will check this out.

**Comment by tadfisher** [comment]
This apparently works in the `lenient-configs` branch. I've added a test, and I will try to get that branch polished up and ready to ship.
