### ISSUE TITLE
fixupPhase messes up "info/*" paths

### ISSUE THREAD

**Issue by danielfullmer** [tadfisher/gradle2nix#2]
If the dependency name is (for example) `info.guardianproject.netcipher-netcipher-2.0.0-beta1-jar`, the path in the generated dependencies tree ends up as `share/info/guardianproject/...` instead of the desired `info/guardianproject/...`. 

This is caused by including `fixupPhase` in `mkDep`. Is fixupPhase needed here for reasons I don't realize? Removing fixupPhase also seems to speed up the time to create these directories.

**Comment by tadfisher** [comment]
I believe I copied that from `fetchMavenArtifact`. It probably doesn't need to happen.

**Comment by tadfisher** [comment]
Fixed in https://github.com/tadfisher/gradle2nix/commit/3afaaa373ae029aab8090d777013fcf5012bae59
