### ISSUE TITLE
Plugin applied in settings.gradle missing from offline repo

### ISSUE THREAD

**Issue by jmglov** [tadfisher/gradle2nix#25]
I have a `settings.gradle` which looks like this:

```
buildscript {
    repositories {
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath 'gradle.plugin.net.vivin:gradle-semantic-build-versioning:4.0.0'
    }
}

apply plugin: 'net.vivin.gradle-semantic-build-versioning'

rootProject.name = 'kws-request'
include 'kws-request-signing-core'
```

When I try to build the Nix derivation produced by gradle2nix, I get this:

```
Starting Build
Compiling initialization script '/nix/store/vcyn2xg4clpi90h0k8l3kl1qsp9lmhr2-init.gradle' using SubsetScriptTransformer.
Compiling initialization script '/nix/store/vcyn2xg4clpi90h0k8l3kl1qsp9lmhr2-init.gradle' using BuildScriptTransformer.
Compiling settings file '/run/user/1002/nix-build-kws-request-0.1.0-SNAPSHOT.drv-1/kws-java/settings.gradle' using SubsetScriptTransformer.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all artifacts for configuration 'classpath'.
> Could not resolve gradle.plugin.net.vivin:gradle-semantic-build-versioning:4.0.0.
  Required by:
      unspecified:unspecified:unspecified
   > No cached version of gradle.plugin.net.vivin:gradle-semantic-build-versioning:4.0.0 available for offline mode.
```

I see no sign of the `net.vivin.gradle-semantic-build-versioning` plugin in `gradle-env.json`.

**Comment by tadfisher** [comment]
Hmm, a settings plugin may be difficult to extract. I'll take a look and see if there's some magic I can cast.

**Comment by tadfisher** [comment]
So, I can do this, but I'm having a hard time applying the offline repo to the settings script from an init script. `beforeSettings { }` was added in Gradle 6.0, and that works, but versions prior to that don't expose a callback that runs when settings are available before actually evaluating the settings. Both `buildStarted` and `settingsEvaluated` run too late.

Are you fine with adding support for settings script plugins only in Gradle 6.0 and above?

**Comment by jmglov** [comment]
I came across the `beforeSettings {}` hook as well when I was investigating this. I think it's perfectly fine to support this only for Gradle 6+. I guess it would make sense for `gradle2nix` to fail with a nice error message if it finds a settings plugin with a too old version of Gradle, right?

Thanks for looking into this!

**Comment by tadfisher** [comment]
Hopefully fixed by https://github.com/tadfisher/gradle2nix/commit/fd6a6f469348690c92551313ccbe295b254d6a16.
