### ISSUE TITLE
gradle2nix hangs with Mindustry v99

### ISSUE THREAD

**Issue by wamserma** [tadfisher/gradle2nix#4]
Tried running gradle2nix on https://github.com/Anuken/Mindustry/tree/v99 with
`nix-shell -p jre --run '../g2n` resulting in 
```
Resolving project model: root project...
Downloading https://services.gradle.org/distributions/gradle-5.5-bin.zip
.....................................................................................
No local.properties found. Not loading Android module.
```
at which point it seemed to hang.

See https://github.com/NixOS/nixpkgs/pull/72198#issuecomment-548568499 for the packaging discussion of Mindustry.

**Comment by tadfisher** [comment]
I believe we need to add an option to explicitly list which subprojects to resolve, as right now `gradle2nix` will attempt to resolve all of them. I'm assuming you don't want to package the Android app here.

**Comment by tadfisher** [comment]
Can you try the `explicit-subprojects` branch with the following:

```
gradle2nix -p :desktop
```

Seems to resolve fine now with this change.

**Comment by tadfisher** [comment]
Also, the hanging may be due to Gradle fetching a whole ton of dependencies. I'm not currently piping the output of the nested Gradle build anywhere, so you won't see anything while that's happening.

**Comment by tadfisher** [comment]
Sorry, the first commit was broken; it should now resolve the dependencies for the subprojects that `:desktop` depends on:

```
[tad@dirac:~/src/Mindustry]$ ../../proj/gradle2nix/result/bin/gradle2nix -p :desktop
Resolving project model: root project...
No local.properties found. Not loading Android module.

> Configure project :
Compiling with build: 'custom build'
    Subproject: :
    Subproject: :desktop
    Subproject: :core
    Subproject: :annotations

CONFIGURE SUCCESSFUL in 3s
Building environment...
Writing environment to ./gradle-env.json
Writing Nix script to ./gradle-env.nix
```

Then with a `default.nix` containing the following:

```nix
{ pkgs ? import <nixpkgs> {} }:

with pkgs;

let
  buildGradle = pkgs.callPackage ./gradle-env.nix {};

in buildGradle {
  envSpec = ./gradle-env.json;

  src = ./.;

  gradleFlags = [ ":desktop:dist" ];

  installPhase = ''
    mkdir -p $out
    cp -r desktop/build/libs/Mindustry.jar $out/
  '';
}
```

I can run `nix build -f default.nix` and *almost* get a working result. Unfortunately, the project uses a `SNAPSHOT` dependency on `robovm-compiler`, which doesn't use the default Maven directory layout that `gradle2nix` assumes. I'll try to figure out how to resolve these.

**Comment by wamserma** [comment]
A working proposal for Mindustry, following the pattern of packaging used in shattered-pixel-dungeon-gdx has been added as https://github.com/NixOS/nixpkgs/pull/72306, no need to hurry.
Nevertheless, building Mindustry can be a good benchmark for gradle2nix, so let's keep the issue open.

**Comment by wamserma** [comment]
> Also, the hanging may be due to Gradle fetching a whole ton of dependencies. I'm not currently piping the output of the nested Gradle build anywhere, so you won't see anything while that's happening.

Yes, that may well be. Gradle2Nix could be a tad more verbose there.
